In [1]:
import cv2

In [2]:
# Check Open cv Version
def main():
    print(cv2.__version__)
    
if __name__=="__main__":
    main()

3.4.2


In [3]:
print(cv2.__version__)

3.4.2


In [4]:
def main():
    imgpath='imgdata\\4.1.01.tiff'
    img=cv2.imread(imgpath)
    cv2.imshow("Lena",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()  
    
    
if __name__=="__main__":
    main()

### Mode of Reading Images 

In [4]:
def main():
    imgpath='imgdata\\4.1.01.tiff'
    img=cv2.imread(imgpath,1)  # 1 for As it is color image 
    cv2.imshow("Lena",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()  
    
    
if __name__=="__main__":
    main()

In [3]:
def main():
    imgpath='imgdata\\4.1.01.tiff'
    img=cv2.imread(imgpath,1)  # 0 for Black and White image 
    cv2.imshow("Lena",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()  
    
    
if __name__=="__main__":
    main()

In [2]:
def main():
    imgpath='imgdata\\4.1.01.tiff'
    img=cv2.imread(imgpath,-1)  # 0 for Black and White image 
    cv2.imshow("Lena",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()  
    
    
if __name__=="__main__":
    main()

### How to store filein different location 

In [2]:
def main():
    imgpath='imgdata\\4.1.01.tiff'
    img=cv2.imread(imgpath)  
    output='C://Users//vhsat//Documents//CyberLink//4.1.01.jpg' # External path 
    cv2.imshow("Lena",img)
    cv2.imwrite(output,img) # imwrite to write img 
    cv2.waitKey(0)
    cv2.destroyAllWindows()  
    
    
if __name__=="__main__":
    main()

Humans = Biology = Patterns

Senses=visual, audio, smell, touch etc

computes= mathematical=numbers

images are number for a computer.
video
sound

In [7]:
def main():
    imgpath='imgdata\\4.1.01.tiff'
    img1=cv2.imread(imgpath)  
    
    print(img1)     # Images are store in set of numbers 
    print(type(img1))  # NumPy = Numerical Python
    cv2.imshow("Lena",img1)
     
    cv2.waitKey(0)
    cv2.destroyAllWindows()  
    
    
if __name__=="__main__":
    main()

[[[ 42  46  52]
  [ 38  40  47]
  [ 34  42  50]
  ...
  [136 131 137]
  [136 137 126]
  [130 134 126]]

 [[ 43  45  55]
  [ 35  44  50]
  [ 38  40  54]
  ...
  [143 139 129]
  [139 134 129]
  [146 142 121]]

 [[ 39  42  46]
  [ 43  42  49]
  [ 55  42  52]
  ...
  [133 137 126]
  [130 131 123]
  [128 134 118]]

 ...

 [[  5   5   4]
  [  4   3   3]
  [  3   3   3]
  ...
  [ 44  64  60]
  [ 91  93  84]
  [ 93 105  98]]

 [[ 10   8  11]
  [ 12  11  12]
  [ 10  10  12]
  ...
  [ 40  68  60]
  [ 64  88  86]
  [ 91 105 100]]

 [[ 16  18  20]
  [ 16  16  19]
  [ 13  14  20]
  ...
  [ 42  56  55]
  [ 58  78  70]
  [ 80 100  93]]]
<class 'numpy.ndarray'>


In [10]:
def main():
    imgpath='imgdata\\4.1.01.tiff'
    img1=cv2.imread(imgpath)  
    
    #print(img1)     # Images are store in set of numbers 
    print(type(img1))  # NumPy = Numerical Python
    print(img1.dtype)
    print(img1.shape)  # in open cv Blue,Green,Red
    print(img1.ndim)
    print(img1.size)  # 256*256*3
    #cv2.imshow("Lena",img1)
     
   # cv2.waitKey(0)
   # cv2.destroyAllWindows()  
    
    
if __name__=="__main__":
    main()

<class 'numpy.ndarray'>
uint8
(256, 256, 3)
3
196608


In [4]:
def main():
    imgpath='imgdata\\4.1.01.tiff'
    img1=cv2.imread(imgpath,0)  # Grayscale image 
    
    print(img1)     # Images are store in set of numbers 
    print(type(img1))  # NumPy = Numerical Python
    print(img1.dtype)
    print(img1.shape)  # in open cv Blue,Green,Red
    print(img1.ndim)
    print(img1.size)  # 256*256
    #cv2.imshow("Lena",img1)
     
   # cv2.waitKey(0)
   # cv2.destroyAllWindows()  
    
    
if __name__=="__main__":
    main()

[[ 47  42  43 ... 133 134 131]
 [ 48  45  44 ... 136 133 136]
 [ 43  44  46 ... 133 128 129]
 ...
 [  5   3   3 ...  61  90 102]
 [  9  11  11 ...  62  85 102]
 [ 18  17  16 ...  54  73  96]]
<class 'numpy.ndarray'>
uint8
(256, 256)
2
65536


### Draw The images 

In [11]:
import numpy as np
def main():
    img1=np.zeros((512,512,3),np.uint8)
    cv2.imshow("Lena",img1)
    cv2.waitKey(0)
    cv2.destroyWindow("Lena")
if __name__=="__main__":
    main()

In [ ]:
import numpy as np
def main():
    img1=np.zeros((512,512,3),np.uint8)
    cv2.line(img1, (0, 99), (99, 0),(255, 0, 0), 2)
    cv2.rectangle(img1,(150,90),(200,170),(0,255,0),2)
    cv2.circle(img1,(60,60),50,(0,0,255),-1)
    cv2.ellipse(img1,(160,260),(50,20),0,0,360,(127,127,127),-1)
    
    # Poly gone 
    points=np.array([[80,2],[125,2],[179,50],[125,100],[50,50]],np.int32)
    points=points.reshape((-1,1,2))
    cv2.polylines(img1,[points],True,(0,255,255))
    
    test1='Test Text'
    cv2.putText(img1, test1, (100,100), cv2.FONT_HERSHEY_SIMPLEX,2,(255,255,0))
    
    
    cv2.imshow("Lena",img1)
    cv2.waitKey(0)
    cv2.destroyWindow("Lena")
if __name__=="__main__":
    main()
    

# Mini Project: OpenCV BGR Palette with Trackbars

In [1]:
import cv2
import numpy as np
def emptyFunction(self):
    pass


def main():
    image=np.zeros((512,512,3),np.uint8)
    windowName="Open CV BGR color Palette"
    cv2.namedWindow(windowName)
    
    cv2.createTrackbar("B",windowName,0,255,emptyFunction)
    cv2.createTrackbar("G",windowName,0,255,emptyFunction)
    cv2.createTrackbar("R",windowName,0,255,emptyFunction)
    
    while(True):
        cv2.imshow(windowName,image)
        
        if cv2.waitKey(1)==27:  # 27 is code for esc key 
            break
            
        blue=cv2.getTrackbarPos("B",windowName)
        green=cv2.getTrackbarPos("G",windowName)
        red=cv2.getTrackbarPos("R",windowName)
        
        image[:]=[blue,green,red]
        print(blue,green,red)
        
        
    cv2.destroyAllWindows()
    
    
if __name__=="__main__":
    main()

0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 

0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 

0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0

0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0

0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0 45 117
0

# Mini Project: Mouse events and Interactive Drawing 

In [8]:
import cv2
import numpy as np

# Create Black image ad window 
windowName="Drawing"
img=np.zeros((512,512,3),np.uint8)
cv2.namedWindow(windowName)

#Mouse call back function
def draw_circle(event,x,y,flags,param):
    if event==cv2.EVENT_LBUTTONDBLCLK:
        cv2.circle(img,(x,y),40,(0,255,0),-1)  #40 rdius , (0,255,0) Green color -1 is for filled 
    if event==cv2.EVENT_RBUTTONDOWN:
        cv2.circle(img,(x,y),30,(255,0,0),1)  # 1 for non filled 
    if event==cv2.EVENT_RBUTTONDBLCLK:
        cv2.circle(img,(x,y),30,(0,0,255),-1)
        
# bind the callback function to window 
cv2.setMouseCallback(windowName,draw_circle)

def main():
    while(True):
        cv2.imshow(windowName,img)
        if cv2.waitKey(20)==27:
            break
    cv2.destroyAllWindows()
    
if __name__=="__main__":
    main()
        