In [1]:
import numpy as np

In [2]:
a=np.arange(10,21,1)
s=slice(2,7,2)
print(a)
print(a[s])

[10 11 12 13 14 15 16 17 18 19 20]
[12 14 16]


In [3]:
b=a[2:7:2]
print(b)

[12 14 16]


In [4]:
# slice single item
a=np.arange(10)
b=a[5]
print(b)
print(a)

5
[0 1 2 3 4 5 6 7 8 9]


In [6]:
# slice items starting from index a=np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]


In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# slice item starting from index
print('Now we will slice the array from the index a[1:]')
print(a[1:])
print(a[1][1])
print(a[1][1:])

Now we will slice the array from the index a[1:]
[[4 5 6]
 [7 8 9]]
5
[5 6]


In [9]:
# this returns array of items in the second column
print('The item in the second column are :')
print(a[...,1])
print('\n')


The item in the second column are :
[2 5 8]




In [10]:
# this returns array of items in the second row
print('The item in the second row are :')
print(a[1,...])      # Row index for second row is 1 
print('\n')


The item in the second row are :
[4 5 6]




In [11]:
# this returns slice all items from column 1 onwards 
print('The items column1 onward are :')
print(a[...,1:])      # Row index for second row is 1 
print('\n')


The items column1 onward are :
[[2 3]
 [5 6]
 [8 9]]




# advance slicing 


In [13]:
x=np.array([[1,2],[3,4],[5,6]])
y=x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]


In [14]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [15]:
rows=np.array([[0,0],[3,3]])
cols=np.array([[0,2],[0,2]])
y=x[rows,cols]

In [16]:
print('The corner elements of this array are:')
print(y)

The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [17]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('our array is:')
print(x)
print('\n')

our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]




In [20]:
# slicing
z=x[1:4,1:3]
print('After Slicing, our array becomes:')
print(z)
print('\n')


After Slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]




In [21]:
# using advance index for column
y=x[1:4,[1,2]]
print('slicing using advance index for column')
print(y)


slicing using advance index for column
[[ 4  5]
 [ 7  8]
 [10 11]]


In [22]:
x=np.array([0,1,2,3,4,5,6,7,8,9,10,11])
print('Our array is :')
print(x)
print('\n')

Our array is :
[ 0  1  2  3  4  5  6  7  8  9 10 11]




In [23]:
# Now we will print item grater than 5
print('The item greater than 5 are:')
print(x[x>5])

The item greater than 5 are:
[ 6  7  8  9 10 11]


In [24]:
a=np.array([np.nan,1,2,np.nan,3,4,5])
print(a[~np.isnan(a)])

[ 1.  2.  3.  4.  5.]


In [25]:
a=np.array([1,2+6j,5,3.5+5j])
print(a[np.iscomplex(a)])

[ 2.0+6.j  3.5+5.j]


# Broadcasting

In [26]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
c=a*b
print(c)

[ 10  40  90 160]


In [27]:
d=5*b
print(d)

[ 50 100 150 200]


In [28]:
a=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b=np.array([1,2,3])
c=np.array([[1],[2],[3],[4]])

In [29]:
print('First array:')
print(a)
print('\n')

First array:
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]




In [30]:
print('second array')
print(b)
print('\n')

second array
[1 2 3]




In [31]:
print('First array + seconf array')
print(a+b)


First array + seconf array
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [32]:
print(a+c)

[[ 1  1  1]
 [12 12 12]
 [23 23 23]
 [34 34 34]]


In [33]:
a=np.array([0,30,45,60,90])
print('Sine of different angles:')
# Convert to radians by multiplying with pi/180
print(np.sin(a*np.pi/180))
print('\n')

print('cosine of different angles:')
print(np.cos(a*np.pi/180))
print('\n')


print('Tangent of different angles:')
print(np.tan(a*np.pi/180))
print('\n')



Sine of different angles:
[ 0.          0.5         0.70710678  0.8660254   1.        ]


cosine of different angles:
[  1.00000000e+00   8.66025404e-01   7.07106781e-01   5.00000000e-01
   6.12323400e-17]


Tangent of different angles:
[  0.00000000e+00   5.77350269e-01   1.00000000e+00   1.73205081e+00
   1.63312394e+16]




# Rounding 

In [34]:
a=np.array([1.0,5.55,123,0.567,25.532])

print('Original array :')
print(a)
print('\n')



Original array :
[   1.       5.55   123.       0.567   25.532]




In [35]:
print('after rounding')
print(np.around(a))
print(np.around(a,decimals=1))

after rounding
[   1.    6.  123.    1.   26.]
[   1.     5.6  123.     0.6   25.5]


In [37]:
print(np.around(a,decimals=-1))
#round up to 10

[   0.   10.  120.    0.   30.]


In [38]:
a=np.array([-1.7,1.5,-0.2,0.6,10])
print('Original array :')
print(a)
print('\n')

print('The modified array:')
print(np.floor(a))

print('The Modified array:')
print(np.ceil(a))


Original array :
[ -1.7   1.5  -0.2   0.6  10. ]


The modified array:
[ -2.   1.  -1.   0.  10.]
The Modified array:
[ -1.   2.  -0.   1.  10.]


# Arithmatic

In [39]:
a=np.arange(9,dtype=np.float).reshape(3,3)

In [40]:
print('First array')
print(a)

First array
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]


In [41]:
print('Second array')
b=np.array([10,5,1])
print(b)

Second array
[10  5  1]


In [43]:
print('add two array')
print(np.add(a,b))

add two array
[[ 10.   6.   3.]
 [ 13.   9.   6.]
 [ 16.  12.   9.]]


In [44]:
print('subtract two array')
print(np.subtract(a,b))

subtract two array
[[-10.  -4.   1.]
 [ -7.  -1.   4.]
 [ -4.   2.   7.]]


In [45]:
print('Multiply two array')
print(np.multiply(a,b))

Multiply two array
[[  0.   5.   2.]
 [ 30.  20.   5.]
 [ 60.  35.   8.]]


In [46]:
print('divide two array')
print(np.divide(a,b))

divide two array
[[ 0.   0.2  2. ]
 [ 0.3  0.8  5. ]
 [ 0.6  1.4  8. ]]


In [47]:
a=np.array([0.25,1.33,1,0,100])
print('our array is:')
print(a)

our array is:
[   0.25    1.33    1.      0.    100.  ]


In [48]:
print('after applying rciprocalfunction :')
print(np.reciprocal(a))

after applying arciprocalfunction :
[ 4.         0.7518797  1.               inf  0.01     ]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in reciprocal
  


In [49]:
b=np.array([100],dtype=int)
print('The second array is :')
print(b)

The second array is :
[100]


In [50]:
print('after applying rciprocal function :')
print(np.reciprocal(b))

after applying arciprocalfunction :
[0]


In [51]:
a=np.array([10,100,1000])
print('Our array is:')
print(a)
print('applying power function:')
print(np.power(a,2))

Our array is:
[  10  100 1000]
applying power function:
[    100   10000 1000000]


In [53]:
print('Our second array is:')
b=np.array([1,2,3])
print('applying power function:')
print(np.power(b,2))

Our second array is:
applying power function:
[1 4 9]


In [ ]:
a=np.array([10,20,30])
b=np.array([3,5,7])


In [54]:
print('Our first array is:')
print(a)
print('Our Second array is:')
print(b)
print('applying mod() function:')
print(np.mod(a,b))

Our first array is:
[  10  100 1000]
Our Second array is:
[1 2 3]
applying mod() function:
[0 0 1]


In [55]:
print('applying remainder() function:')
print(np.remainder(a,b))

applying remainder() function:
[0 0 1]
