# Program 1: Temprature

In [1]:
import numpy as np

In [2]:
cvalues=[15.3,29.4,24.8,13.9]
print(type(cvalues))

<class 'list'>


In [3]:
C=np.array(cvalues)
print(C)
print(type(C))

[15.3 29.4 24.8 13.9]
<class 'numpy.ndarray'>


In [4]:
# General conversion from C to F
fvalues=[]
for x in cvalues:
    fvalues.append(x*9/5+32)
print(fvalues)

[59.540000000000006, 84.91999999999999, 76.64, 57.02]


In [5]:
# NumPy simple calculation
print(C*9/5+32)                  # It Takes the value from ndarray C one by one and apply the formula

[59.54 84.92 76.64 57.02]


In [6]:
print(C)

[15.3 29.4 24.8 13.9]


# Program 2: Types of Input

In [7]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
# More than one dimension
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [11]:
# minimum Dimension
c=np.array([1,2,3,4,5,5,9,6],ndmin=4)
print(c)

[[[[1 2 3 4 5 5 9 6]]]]


In [12]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [12]:
#dtype parameter
d=np.array([1,2,3],dtype=complex)
print(d)

[ 1.+0.j  2.+0.j  3.+0.j]


In [19]:
e=(d.copy())

In [20]:
print(e)

[ 1.+0.j  2.+0.j  3.+0.j]


In [25]:
f=np.array([])

In [26]:
print(f.any())

False


In [27]:
dt=np.dtype(np.int32)
print(dt)

int32


In [34]:
#int8,int16,int32,int64 can be replace
#by equivalent string 'i1','i2','i4' etc

dt=np.dtype('i4')
print(dt)

int32


In [49]:
#using endian notation

dt=np.dtype('>i4')
print(dt)

>i4


In [50]:
dt.kind

'i'

In [46]:
dt=np.dtype('i8')
print(dt)

int64


In [15]:
# create structured data type 
dt=np.dtype([("age",np.int8)])
print(dt)


[('age', 'i1')]


In [16]:
# now apply it to ndarray object
a=np.array([(257,),(20,),(30,)],dtype=dt)
print(a)

[( 1,) (20,) (30,)]


In [17]:
# array name can be used to access content of age column
print(a['age'])

[ 1 20 30]


In [18]:
x=np.dtype(np.int8)

print(x)
a=np.array([199,12,312],dtype=x)
print(a)

int8
[-57  12  56]


In [63]:
x=np.dtype(np.int8)
print(x)
print(type(x))

int8
<class 'numpy.dtype'>


In [64]:
x=102478365275618633526732368286815338375336687265367665
print(type(x))
print(x)

<class 'int'>
102478365275618633526732368286815338375336687265367665


In [42]:
dt=np.dtype(np.int64)
print(dt)

int64


In [3]:
# create structured data type 
dt=np.dtype([("age",np.int8)])
print(dt)
# now apply it to ndarray object
a=np.array([(257,),(20,),(30,)],dtype=dt)
print(a)
# array name can be used to access content of age column
print(a['age'])

[('age', 'i1')]
[( 1,) (20,) (30,)]
[ 1 20 30]


In [4]:
x1=(10)
x2=(20)
print(x1,type(x1))
print(x2,type(x2))

10 <class 'int'>
20 <class 'int'>


In [21]:
student=np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [22]:
a=np.array([('abc',21,50),('xyz',18,75)],dtype=student)
print(a)

[(b'abc', 21,  50.) (b'xyz', 18,  75.)]


In [23]:
print(a['age'])

[21 18]


In [24]:
print(a['name'][1])

b'xyz'


# Attributes

In [26]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [27]:
# this resize the ndarray
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [28]:
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [29]:
# an array of evenly spaced numbers
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [32]:
# above is one dimensional array
print(a.ndim)

1


In [33]:
# now reshape it 
b=a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [34]:
# now reshape it 
b=a.reshape(3,4,2)  #plane * Row *column
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [19]:
#b is having three dimensions
print(b.ndim)

2


In [20]:
# dtype of array is int8 (1 byte)
x=np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)
print(x)

1
[1 2 3 4 5]


In [21]:
# dtype of array is float32 (4 byte)
x=np.array([1,2,3,4,5],dtype=np.float32)
print(x.itemsize)

4


In [45]:
student=np.dtype([('name','S20'),('age','i1'),('marks','f4')])
a=np.array([('abc',21,50),('xyz',18,75)],dtype=student)
print(a.itemsize)

25


In [50]:
x=np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [51]:
print(x.flags['WRITEABLE'])

True


In [52]:
x[3]=10
print(x)


[ 1  2  3 10  5]


In [53]:
x.flags['WRITEABLE']=False
x[3]=12
print(x)

ValueError: assignment destination is read-only

# array Creation

In [54]:
x=np.empty((3,2),dtype=int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [56]:
# array of five zeros,default type is float
x=np.zeros(5)
print(x)

[ 0.  0.  0.  0.  0.]


In [57]:
x=np.zeros(5,dtype=int)
print(x)

[0 0 0 0 0]


In [58]:
#custom type 
x=np.zeros((2,2),dtype=[('x','i4'),('y','i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [64]:
x['x'][0][0]=5
print(x)

[[(5, 0) (5, 0)]
 [(0, 0) (0, 0)]]


In [65]:
x['x'][0]=(2,3)
print(x)

[[(2, 0) (3, 0)]
 [(0, 0) (0, 0)]]


In [66]:
x['x']=[(4,5),(6,7)]
print(x)

[[(4, 0) (5, 0)]
 [(6, 0) (7, 0)]]


In [68]:
# array of five ones, default type is float
x=np.ones(5)
print(x)

[ 1.  1.  1.  1.  1.]


In [70]:
x=np.ones((2,2),dtype=int)
print(x)


[[1 1]
 [1 1]]


In [78]:
z=np.arange(10,20,2,dtype='int8')
print(z)

[10 12 14 16 18]


In [79]:
z.itemsize

1

In [75]:
# convert list to array 
x=[1,2,3]
a=np.asarray(x)
print(a)

[1 2 3]


In [81]:
# dtype is set
a=np.asarray(x,dtype=float)
print(a)

[ 1.  2.  3.]


In [82]:
# ndarray from tuple 
x=(1,2,3)
a=np.asarray(x)
print(a)


[1 2 3]


In [84]:
# ndarray from list of tuples
x=[(1,2,3),(4,5)]
print(x)

[(1, 2, 3), (4, 5)]


In [85]:
s=b'Hello World'
a=np.frombuffer(s,count=3,offset=4,dtype='S1')
print(a)


'''frombuffer(...)
    frombuffer(buffer, dtype=float, count=-1, offset=0)
    
    Interpret a buffer as a 1-dimensional array.
    
    Parameters
    ----------
    buffer : buffer_like
        An object that exposes the buffer interface.
    dtype : data-type, optional
        Data-type of the returned array; default: float.
    count : int, optional
        Number of items to read. ``-1`` means all data in the buffer.
    offset : int, optional
        Start reading the buffer from this offset (in bytes); default: 0.'''

[b'o' b' ' b'W']


In [87]:
help(np.frombuffer)

Help on built-in function frombuffer in module numpy.core.multiarray:

frombuffer(...)
    frombuffer(buffer, dtype=float, count=-1, offset=0)
    
    Interpret a buffer as a 1-dimensional array.
    
    Parameters
    ----------
    buffer : buffer_like
        An object that exposes the buffer interface.
    dtype : data-type, optional
        Data-type of the returned array; default: float.
    count : int, optional
        Number of items to read. ``-1`` means all data in the buffer.
    offset : int, optional
        Start reading the buffer from this offset (in bytes); default: 0.
    
    Notes
    -----
    If the buffer has data that is not in machine byte-order, this should
    be specified as part of the data-type, e.g.::
    
      >>> dt = np.dtype(int)
      >>> dt = dt.newbyteorder('>')
      >>> np.frombuffer(buf, dtype=dt)
    
    The data of the resulting array will not be byteswapped, but will be
    interpreted correctly.
    
    Examples
    --------
    >>> s 

# Array From Numerical Ranges

In [5]:
# numpy.arange(start,stop,step,dtype)
b=np.arange(10,512,1,dtype='i2')
print(b)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225
 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 247 248 249 250 251 252 253 254 255 25

In [13]:
# numpy.linspace(start,stop,num,endpoint,restep,dtype)
# num=50 Default
# endvalue : true by default, hence the stop value is included in the sequence. if false, it is not included 
# restep : if true, returns samples and step between the consecutive numbers 


# numpy.linspace(start,stop,num,endpoint,restep,dtype)
a=np.linspace(10,200,96,True,True,dtype='i2')
print(a)

(array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108, 110, 112,
       114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138,
       140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164,
       166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190,
       192, 194, 196, 198, 200], dtype=int16), 2.0)


In [14]:
x=np.arange(5)
print(x)

[0 1 2 3 4]


In [16]:
#dtype set
x=np.arange(5,dtype=float)
print(x)

[ 0.  1.  2.  3.  4.]


In [17]:
#start and stop parameter set 
# numpy.arange(start,stop,step,dtype)
x=np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [19]:
x=np.linspace(10,20,5)   # 10 to 20 make 5 equal parts 
print(x)

[ 10.   12.5  15.   17.5  20. ]


In [20]:
#endpoint set to false 
x=np.linspace(10,20,5,endpoint=False)
print(x)

[ 10.  12.  14.  16.  18.]


In [22]:
help(np.dtype)

Help on class dtype in module numpy:

class dtype(builtins.object)
 |  dtype(obj, align=False, copy=False)
 |  
 |  Create a data type object.
 |  
 |  A numpy array is homogeneous, and contains elements described by a
 |  dtype object. A dtype object can be constructed from different
 |  combinations of fundamental numeric types.
 |  
 |  Parameters
 |  ----------
 |  obj
 |      Object to be converted to a data type object.
 |  align : bool, optional
 |      Add padding to the fields to match what a C compiler would output
 |      for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
 |      or a comma-separated string. If a struct dtype is being created,
 |      this also sets a sticky alignment flag ``isalignedstruct``.
 |  copy : bool, optional
 |      Make a new copy of the data-type object. If ``False``, the result
 |      may just be a reference to a built-in data-type object.
 |  
 |  See also
 |  --------
 |  result_type
 |  
 |  Examples
 |  --------
 |  Usin